import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      /////////header
      'Trading Strategies': 'Trading Strategies',
      'Educational Videos': 'Educational Videos',
      'login': 'Sign Up (current)',
      ///////////////landing
      'Trading made simple': 'Trading made simple',
      'Join  Universe  Trading now and gain smart and passive benefits!': 'Join  Universe  Trading now and gain smart and passive benefits!',
      'Open Account': 'Open Account',
      'Start Onboarding Now': 'Start Onboarding Now',
      ///////////why is ut
      'Why is Universal Trading your partner for successful trading?': 'Why is Universal Trading your partner for successful trading?',
      'Proven Success': 'Proven Success',
      'Live Chat Support': 'Live Chat Support',
      'No Prior Knowledge Required': 'No Prior Knowledge Required',
      'More than two years of externally verified trading results.': 'More than two years of externally verified trading results.',
      'Enjoy the best live chat support. No matter what you need, we are here for you.': 'Enjoy the best live chat support. No matter what you need, we are here for you.',
      'In 3 simple steps to your own trading portfolio.': 'In 3 simple steps to your own trading portfolio.',
      //////////////////tradeup
      'Trade up your life!': 'Trade up your life!',
      'Deposit today and our trading software will start working for you!': 'Deposit today and our trading software will start working for you!',
      'Discover the advantages of our unique technology and how partnering with us can help to achieve your goals': 'Discover the advantages of our unique technology and how partnering with us can help to achieve your goals',
      'Open Your Trading Account Now': 'Open Your Trading Account Now',
      'What is Universe Trading ?': 'What is Universe Trading ?',
      'Universe Trading is a premium software provider for crypto and forex trading.': 'Universe Trading is a premium software provider for crypto and forex trading.',
      'Trust Your Universe does not charge any entry or monthly fees! Sign up and use our software for free.': 'Trust Your Universe does not charge any entry or monthly fees! Sign up and use our software for free.',
      'The software trades fully automated 24/5 aiming for the ideal relationship of chance to risk..': 'The software trades fully automated 24/5 aiming for the ideal relationship of chance to risk..',
      'The company only makes money, by receiving a small cut of the positive sum of all trades generated by the software for the client.': 'The company only makes money, by receiving a small cut of the positive sum of all trades generated by the software for the client.',
      'login': 'Open Account',
      'MyFxBook is an independent third-party tracking provider that allows all traders worldwide to connect their trading accounts to transparently document their own trading results independently.': 'MyFxBook is an independent third-party tracking provider that allows all traders worldwide to connect their trading accounts to transparently document their own trading results independently.',
      'Every single day/week/month even every single trade is publicly and transparently viewable.': 'Every single day/week/month even every single trade is publicly and transparently viewable.',
      'MyFxBook is the most transparent platform available in the crypto and forex trading market.': 'MyFxBook is the most transparent platform available in the crypto and forex trading market.',
      'Create your account now': 'Create your account now',
      'It has never been easier to earn money by trading.': 'It has never been easier to earn money by trading.',
      'This website is operated by an affiliate partner.': 'This website is operated by an affiliate partner.',
      'It has never been easier. Let our trading software work for you.': 'It has never been easier. Let our trading software work for you.',
      'What makes Universe Trading the right partner for your trading needs?': 'What makes Universe Trading the right partner for your trading needs?',
      'More than two years of externally verified trading results': 'More than two years of externally verified trading results',
      'Enjoy the best live chat support. No matter what you need, we are here for you': 'No Prior Knowledge Required',
      'In 3 simple steps to your own trading portfolio': 'In 3 simple steps to your own trading portfolio',
      'No Prior Knowledge Required': 'No Prior Knowledge Required',
      'No Prior Knowledge Required': 'No Prior Knowledge Required',
      'No Prior Knowledge Required': 'No Prior Knowledge Required',






      //////////////////////////////////////////////////////////////////////////////////////////////////////////////


    },
    'hi_IN': {

      'Trading Strategies': 'ट्रेडिंग रणनीतियाँ',
      'Educational Videos': 'शैक्षिक वीडियो',
      'login': 'लॉग इन करें',

      'Trading made simple': 'व्यापार सरल बना दिया',
      'Join  Universe  Trading now and gain smart and passive benefits!': 'अभी यूनिवर्स ट्रेडिंग से जुड़ें और स्मार्ट और निष्क्रिय लाभ प्राप्त करें!',
      'Open Account': 'लॉग इन करे',
      'Start Onboarding Now': 'लॉग इन करे',

      'Why is Universal Trading your partner for successful trading?': 'सफल ट्रेडिंग के लिए यूनिवर्सल ट्रेडिंग आपका भागीदार क्यों है?',
      'Proven Success': 'सिद्ध सफलता',
      'Live Chat Support': 'लाइव चैट समर्थन',
      'No Prior Knowledge Required': 'कोई पूर्व ज्ञान आवश्यक नहीं है',
      'More than two years of externally verified trading results.': 'बाह्य रूप से सत्यापित व्यापारिक परिणामों के दो वर्ष से अधिक।',
      'Enjoy the best live chat support. No matter what you need, we are here for you.': 'सर्वश्रेष्ठ लाइव चैट समर्थन का आनंद लें। कोई फर्क नहीं पड़ता कि आपको क्या चाहिए, हम यहां आपके लिए हैं।',
      'In 3 simple steps to your own trading portfolio.': 'अपने खुद के ट्रेडिंग पोर्टफोलियो के लिए 3 सरल चरणों में।',

      'Trade up your life!': 'अपने जीवन का व्यापार करें!',
      'Deposit today and our trading software will start working for you!': 'आज ही जमा करें और हमारा ट्रेडिंग सॉफ्टवेयर आपके लिए काम करना शुरू कर देगा!',
      'Discover the advantages of our unique technology and how partnering with us can help to achieve your goals': 'हमारी अनूठी तकनीक के फायदों के बारे में जानें और जानें कि हमारे साथ साझेदारी करने से आपको अपने लक्ष्य हासिल करने में कैसे मदद मिल सकती है',
      'Open Your Trading Account Now': 'अपना ट्रेडिंग खाता अभी खोलें',
      'What is Universe Trading ?': 'यूनिवर्स ट्रेडिंग क्या है?',
      'Universe Trading is a premium software provider for crypto and forex trading.': 'यूनिवर्स ट्रेडिंग क्रिप्टो और फॉरेक्स ट्रेडिंग के लिए एक प्रीमियम सॉफ्टवेयर प्रदाता है।',
      'Trust Your Universe does not charge any entry or monthly fees! Sign up and use our software for free.': 'ट्रस्ट योर यूनिवर्स कोई प्रविष्टि या मासिक शुल्क नहीं लेता है! साइन अप करें और हमारे सॉफ़्टवेयर का निःशुल्क उपयोग करें।',
      'The software trades fully automated 24/5 aiming for the ideal relationship of chance to risk..': 'सॉफ्टवेयर पूरी तरह से स्वचालित 24/5 ट्रेड करता है जो जोखिम के अवसर के आदर्श संबंध के लिए लक्ष्य रखता है।',
      'The company only makes money, by receiving a small cut of the positive sum of all trades generated by the software for the client.': 'क्लाइंट के लिए सॉफ्टवेयर द्वारा उत्पन्न सभी ट्रेडों के सकारात्मक योग का एक छोटा सा हिस्सा प्राप्त करके कंपनी केवल पैसा कमाती है।',
      'login': 'लॉग इन करे',
      'MyFxBook is an independent third-party tracking provider that allows all traders worldwide to connect their trading accounts to transparently document their own trading results independently.': 'MyFxBook एक स्वतंत्र तृतीय-पक्ष ट्रैकिंग प्रदाता है जो दुनिया भर के सभी व्यापारियों को अपने व्यापारिक खातों को स्वतंत्र रूप से अपने स्वयं के व्यापारिक परिणामों को पारदर्शी रूप से दस्तावेज करने की अनुमति देता है।',
      'Every single day/week/month even every single trade is publicly and transparently viewable.': 'हर एक दिन/सप्ताह/महीना यहां तक ​​कि हर एक व्यापार सार्वजनिक और पारदर्शी रूप से देखा जा सकता है।',
      'MyFxBook is the most transparent platform available in the crypto and forex trading market.': 'MyFxBook क्रिप्टो और फॉरेक्स ट्रेडिंग मार्केट में उपलब्ध सबसे पारदर्शी प्लेटफॉर्म है।',
      'Create your account now': 'अभी अपना अकाउंट बनाएं',
      'It has never been easier to earn money by trading.': 'व्यापार करके पैसा कमाना कभी आसान नहीं रहा।',
      'This website is operated by an affiliate partner.': 'यह वेबसाइट एक संबद्ध भागीदार द्वारा संचालित है।',
      'It has never been easier. Let our trading software work for you.': 'यह कभी भी आसान नहीं रहा। हमारे ट्रेडिंग सॉफ्टवेयर को आपके लिए काम करने दें।',
      'What makes Universe Trading the right partner for your trading needs?': 'यूनिवर्स ट्रेडिंग को आपकी व्यापारिक जरूरतों के लिए सही भागीदार क्या बनाता है?',
      'More than two years of externally verified trading results': 'बाह्य रूप से सत्यापित व्यापारिक परिणामों के दो वर्ष से अधिक',
      'Enjoy the best live chat support. No matter what you need, we are here for you': 'सर्वश्रेष्ठ लाइव चैट समर्थन का आनंद लें। कोई फर्क नहीं पड़ता कि आपको क्या चाहिए, हम यहां आपके लिए हैं',
      'No prior knowledge Required': 'कोई पूर्व ज्ञान आवश्यक नहीं है',
      'In 3 simple steps to your own trading portfolio': 'अपने खुद के ट्रेडिंग पोर्टफोलियो के लिए 3 सरल चरणों में',
      'No Prior Knowledge Required': 'No Prior Knowledge Required',







    }
  };
}