import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:tradingwrebsite/webresponsive/weblanding.dart';
import 'package:url_launcher/url_launcher.dart';

void launchURL(String url) async {
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}

class phonewhatut extends StatelessWidget {
  const phonewhatut({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return     Container( height: MediaQuery.of(context).size.height*0.99,width: MediaQuery.of(context).size.width*1,
      decoration: BoxDecoration(

        image: DecorationImage(

          image: AssetImage('logo/what2.jpg'),
          fit: BoxFit.cover,
        ),
      ),

        child: Column(crossAxisAlignment: CrossAxisAlignment.center,mainAxisAlignment: MainAxisAlignment.start,children: [
          SizedBox(height: MediaQuery.of(context).size.height*00.04,),
Text('What is Universe Trading?',style: GoogleFonts.montserrat(color: Colors.white,fontWeight: FontWeight.bold,fontSize: 30),textAlign: TextAlign.center,),
          SizedBox(height: MediaQuery.of(context).size.height*00.05,),
          SizedBox(width: 500,height: 100,
            child: ListTile(
              leading: Container( decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF9D70FF),),
                child: Icon(Icons.arrow_right,color: Colors.white,size: 30,),
              ),
              title: Text('Universe Trading is a premium software provider for crypto and forex trading.'.tr,style: GoogleFonts.montserrat(color: Colors.white),),



            ),
          ),
          SizedBox(width: 500,height: 100,
            child: ListTile(
              leading: Container( decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF9D70FF),),
                child: Icon(Icons.arrow_right,color: Colors.white,size: 30,),
              ),
              title: Text('Trust Your Universe does not charge any entry or monthly fees! Sign up and use our software for free.'.tr
                ,style: GoogleFonts.montserrat(color: Colors.white),),



            ),
          ),
          SizedBox(width: 500,height: 100,
            child: ListTile(
              leading: Container( decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF9D70FF),),
                child: Icon(Icons.arrow_right,color: Colors.white,size: 30,),
              ),
              title: Text('The software trades fully automated 24/5 aiming for the ideal relationship of chance to risk..'.tr
                ,style: GoogleFonts.montserrat(color: Colors.white),),



            ),
          ),
          SizedBox(width: 500,height: 100,
            child: ListTile(
              leading: Container( decoration: BoxDecoration(shape: BoxShape.circle, color: Color(0xFF9D70FF),),
                child: Icon(Icons.arrow_right,color: Colors.white,size: 30,),
              ),
              title: Text('The company only makes money, by receiving a small cut of the positive sum of all trades generated by the software for the client.'.tr
                ,style: GoogleFonts.montserrat(color: Colors.white),),



            ),
          ),
          SizedBox(height: 20,),
          GestureDetector(onTap: () {
            launchURL('https://my.the-universe.trade/register?referral=36');
          },
            child: Container(height: 40,width: 170,

              decoration: BoxDecoration( color: Color(0xFF9D70FF),

                borderRadius: BorderRadius.circular(10),



              ),

              child: Center(child: Text('login'.tr,style: GoogleFonts.montserrat(color: Colors.white,fontSize: 16),)),



            ),
          ),




        ],),
    
    );
  }
}
